"""phase4_specialized_agents

Revision ID: 06bf5308ad3b
Revises: edceec93aecb
Create Date: 2026-09-02 21:24:58.051599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bf5308ad3b'
down_revision: Union[str, Sequence[str], None] = 'edceec93aecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('current_cash_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_accounts_workspace_id'), ['workspace_id'], unique=True)

    op.create_table('marketing_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('research_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_findings', sa.Text(), nullable=True),
    sa.Column('swot_category', sa.String(length=50), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_items_competitor_name'), ['competitor_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_items_swot_category'), ['swot_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_items_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('risk_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('detected_by', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_items_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_items_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_project_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    op.drop_table('expenses')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_project_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_category'))

    op.drop_table('budgets')
    with op.batch_alter_table('risk_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_items_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_risk_items_status'))
        batch_op.drop_index(batch_op.f('ix_risk_items_severity'))
        batch_op.drop_index(batch_op.f('ix_risk_items_risk_score'))
        batch_op.drop_index(batch_op.f('ix_risk_items_category'))

    op.drop_table('risk_items')
    with op.batch_alter_table('research_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_items_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_research_items_topic'))
        batch_op.drop_index(batch_op.f('ix_research_items_swot_category'))
        batch_op.drop_index(batch_op.f('ix_research_items_competitor_name'))

    op.drop_table('research_items')
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_status'))

    op.drop_table('marketing_campaigns')
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_accounts_workspace_id'))

    op.drop_table('financial_accounts')
    # ### end Alembic commands ###
