"""phase3_ai_core

Revision ID: edceec93aecb
Revises: b79f9204755d
Create Date: 2026-09-02 21:17:36.456542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edceec93aecb'
down_revision: Union[str, Sequence[str], None] = 'b79f9204755d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ai_agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_agent_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_agent_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ai_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_payload', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by_agent', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['ai_agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_approvals_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_approvals_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ai_tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['ai_agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tool_calls_agent_run_id'), ['agent_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tool_calls_agent_run_id'))

    op.drop_table('ai_tool_calls')
    with op.batch_alter_table('ai_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_approvals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ai_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_ai_approvals_agent_run_id'))

    op.drop_table('ai_approvals')
    with op.batch_alter_table('ai_agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_agent_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ai_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_agent_runs_conversation_id'))

    op.drop_table('ai_agent_runs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
